Open new files in a pending state in goToLocation
facebook-atom/atom-ide-ui pull request #47
Opened 2017-09-19 03:56 UTC by mehcode

Tracked the source of this behaviour down when using ctrl-click in Atom IDE. I feel that pending tabs are the right UX when I'm navigating around a codebase. Remember that pending tabs can be turned off globally in Atom if a user dislikes them.

---

Unsure the proper way to contribute here so I submitted this and https://github.com/facebook/nuclide/pull/1306

2017-09-19 21:05 UTC, hansonw commented
I think this makes a lot of sense (especially given that VSCode already does this). However since Hyperclick users have probably become accustomed to this behavior I'm hesitant to make this the default; it might make more sense as a configurable value. I'll have to make some changes to enable config options at the `atom-ide-ui` level first; will get back to you.

@matthewwithanm does this make sense in the context of diagnostic errors too?

2017-09-20 00:16 UTC, matthewwithanm commented
Yeah, I think so. Honestly, I think making it the default behavior is okay and just saying that we abide by Atom's global setting.

2017-09-20 00:23 UTC, hansonw commented
OK how about this:

1) Let's make `pending` an option in `goToLocation`, defaulting to false. There a ton of callsites of this function across atom-ide-ui/Nuclide and I'm not sure if it'd be a good idea to have this apply to all of them.
It's probably a good idea to make an `options` parameter that includes `center` since the number of arguments is getting big 😊 
2) Have the `goToLocation` used in `hyperclick` specify the pending option.

Then I think we'd be comfortable rolling this out without a config. Maybe other callsites of `goToLocation` can migrate over to using `pending` as appropriate.

Does that sound OK to you, @mehcode?

2017-09-22 23:01 UTC, hansonw requested changes
@matthewwithanm just added a `pending` option for `goToLocation` - maybe you can just fix the use case in `atom-ide-definitions` to specify it. I'll approve it :)

https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/nuclide-commons-atom/go-to-location.js#L25

Callsite: https://github.com/facebook-atom/atom-ide-ui/blob/master/modules/atom-ide-ui/pkg/atom-ide-definitions/lib/main.js#L128

2017-09-29 01:29 UTC, meycil39 approved these changes

2017-09-29 01:31 UTC, meycil39 approved these changes

2018-11-15 05:29 UTC, closed without merging